name: 'Get Apk Version'
description: 'Get Apk Version'
author: 'JantHsueh | lumotime'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  apkPath:
    description: 'apk path'
    required: true
    default: 'app/build/outputs/apk/release/app-release.apk'
outputs:
  versionCode:
    description: 'apk versionCode'
  versionName:
    description: 'apk versionName'
  applicationId:
    description: 'apk applicationId'
  compileSdkVersion:
    description: 'apk compileSdkVersion'
  minSdkVersion:
    description: 'apk minSdkVersion'
  targetSdkVersion:
    description: 'apk targetSdkVersion'
  icon:
    description: 'apk icon'
  name:
    description: 'apk name'
runs:
  using: 'node12'
  main: 'dist/index.js'
